/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: thelightning (https://sketchfab.com/thelightning)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/subaru-brz-79fb59dd3723495897ec33f1c278b457
title: Subaru BRZ
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/brz.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.013}>
          <group position={[0, 0.91, 93.61]} scale={[634.16, 107.09, 268.4]}>
            <group position={[0.08, 0.22, 0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <group position={[0.06, 0, 0]} rotation={[-1.08, 0, 0]} scale={0.75}>
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4004__TNRRims_14A18NaTire_Material002_0.geometry} material={materials['TNRRims_14A18NaTire_Material.002']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4004_Material010_0.geometry} material={materials['Material.010']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4004_Material011_0.geometry} material={materials['Material.011']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4004_Color_002_0.geometry} material={materials.Color_002} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4004_Toyota_Supra_2020_with_Interior_@noTTo3Ds_chrome_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_chrome} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4004_Toyota_Supra_2020_with_Interior_@noTTo3Ds_plasticblack_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_plasticblack} />
              </group>
            </group>
            <group position={[0.08, 0.22, 0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.04, 0.1, 0.25]}>
              <group position={[0.24, 0, 0]} rotation={[-0.75, 0, 0]} scale={[1.76, 2.83, 2.83]}>
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4_Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material.003']} />
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4_Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material.003']} />
              </group>
            </group>
            <group position={[-0.08, 0.22, 0.37]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.16, 0.37, 0.93]}>
              <group position={[0.06, 0, 0]} rotation={[-1.08, 0, 0]} scale={0.75}>
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4001__TNRRims_14A18NaTire_Material002_0.geometry} material={materials['TNRRims_14A18NaTire_Material.002']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4001_Material010_0.geometry} material={materials['Material.010']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4001_Material011_0.geometry} material={materials['Material.011']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4001_Color_002_0.geometry} material={materials.Color_002} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4001_Toyota_Supra_2020_with_Interior_@noTTo3Ds_chrome_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_chrome} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4001_Toyota_Supra_2020_with_Interior_@noTTo3Ds_plasticblack_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_plasticblack} />
              </group>
            </group>
            <group position={[-0.08, 0.22, 0.37]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.04, 0.1, 0.25]}>
              <group position={[0.24, 0, 0]} rotation={[1.36, 0, 0]} scale={[1.76, 2.83, 2.83]}>
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4002_Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material.003']} />
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4002_Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material.003']} />
              </group>
            </group>
            <group position={[0.08, 0.22, -0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <group position={[0.06, 0, 0]} rotation={[-1.08, 0, 0]} scale={0.75}>
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4002__TNRRims_14A18NaTire_Material002_0.geometry} material={materials['TNRRims_14A18NaTire_Material.002']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4002_Material010_0.geometry} material={materials['Material.010']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4002_Material011_0.geometry} material={materials['Material.011']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4002_Color_002_0.geometry} material={materials.Color_002} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4002_Toyota_Supra_2020_with_Interior_@noTTo3Ds_chrome_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_chrome} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4002_Toyota_Supra_2020_with_Interior_@noTTo3Ds_plasticblack_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_plasticblack} />
              </group>
            </group>
            <group position={[0.08, 0.22, -0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.04, 0.1, 0.25]}>
              <group position={[0.24, 0, 0]} rotation={[1.9, 0, 0]} scale={[1.76, 2.83, 2.83]}>
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4003_Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material.003']} />
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4003_Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material.003']} />
              </group>
            </group>
            <group position={[-0.08, 0.22, -0.37]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.16, 0.37, 0.93]}>
              <group position={[0.06, 0, 0]} rotation={[-1.08, 0, 0]} scale={0.75}>
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4003__TNRRims_14A18NaTire_Material002_0.geometry} material={materials['TNRRims_14A18NaTire_Material.002']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4003_Material010_0.geometry} material={materials['Material.010']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4003_Material011_0.geometry} material={materials['Material.011']} />
                <mesh geometry={nodes.CombinedTireTire_Front_L_Instance1_Src4003_Color_002_0.geometry} material={materials.Color_002} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4003_Toyota_Supra_2020_with_Interior_@noTTo3Ds_chrome_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_chrome} />
                <mesh geometry={nodes['CombinedTireTire_Front_L_Instance1_Src4003_Toyota_Supra_2020_with_Interior_@noTTo3Ds_plasticblack_0'].geometry} material={materials.Toyota_Supra_2020_with_Interior_noTTo3Ds_plasticblack} />
              </group>
            </group>
            <group position={[-0.08, 0.22, -0.37]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.04, 0.1, 0.25]}>
              <group position={[0.24, 0, 0]} rotation={[-1.32, 0, 0]} scale={[1.76, 2.83, 2.83]}>
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4004_Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperGloss_Material.003']} />
                <mesh geometry={nodes.CombinedCalliperCalliper_Front_L_Instance1_Src4004_Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020_CallipersCalliperBadgeA_Material.003']} />
              </group>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane002_Material_0.geometry} material={materials.Material} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane003_Subaru_BRZTNR0_2020Grille6A_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020Grille6A_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane004_Subaru_BRZTNR0_2020Grille8A_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020Grille8A_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane005_Subaru_BRZTNR0_2020Grille9A_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020Grille9A_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane006_Subaru_BRZTNR0_2020PaintTNR_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020PaintTNR_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane008_Subaru_BRZTNR0_2020InteriorTillingA_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020InteriorTillingA_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane009_Subaru_BRZTNR0_2020BadgeA_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020BadgeA_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane010_Subaru_BRZTNR0_2020Base_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020Base_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane011_Subaru_BRZTNR0_2020Coloured_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020Coloured_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane012_Subaru_BRZTNR0_2020Coloured_Material004_0.geometry} material={materials['Subaru_BRZTNR0_2020Coloured_Material.004']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane013_Subaru_BRZTNR0_2020EngineA_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020EngineA_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane014_Subaru_BRZTNR0_2020Grille1A_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020Grille1A_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane015_Subaru_BRZTNR0_2020Grille5A_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020Grille5A_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane016_Subaru_BRZTNR0_2020Grille7A_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020Grille7A_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane018_Subaru_BRZTNR0_2020LightEmissiveA_Material005_0.geometry} material={materials['Subaru_BRZTNR0_2020LightEmissiveA_Material.005']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane019_Subaru_BRZTNR0_2020LightEmissiveA_Material004_0.geometry} material={materials['Subaru_BRZTNR0_2020LightEmissiveA_Material.004']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.22, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane020_Subaru_BRZTNR0_2020ManufacturerPlateA_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020ManufacturerPlateA_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane021_Subaru_BRZTNR0_2020Window_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020Window_Material.003']} />
              <mesh geometry={nodes.Plane021_Material028_0.geometry} material={materials['Material.028']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane022_Subaru_BRZTNR0_2020WindowInside_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020WindowInside_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane023_Subaru_BRZTNR0_2020SeatBelt_Material002_0.geometry} material={materials['Subaru_BRZTNR0_2020SeatBelt_Material.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane024_Material003_0.geometry} material={materials['Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane025_Material009_0.geometry} material={materials['Material.009']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane026_Subaru_BRZTNR0_2020BadgeA_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020BadgeA_Material.003']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane027_Material001_0.geometry} material={materials['Material.001']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane028_Subaru_BRZTNR0_2020LightEmissiveA_Material003_0.geometry} material={materials['Subaru_BRZTNR0_2020LightEmissiveA_Material.003']} />
            </group>
            <group position={[0, 0.61, -0.48]} rotation={[-2.36, 1.57, -2.36]} scale={[-0.39, 0.01, 0.04]}>
              <mesh geometry={nodes['Plane088_Toyota_Supra_2020_with_Interior_@noTTo3Ds_carpaint001_0'].geometry} material={materials['Toyota_Supra_2020_with_Interior_noTTo3Ds_carpaint.001']} />
              <mesh geometry={nodes.Plane088_Material_0.geometry} material={materials.Material} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.16, 0.37, 0.93]}>
              <mesh geometry={nodes.Plane007_Subaru_BRZTNR0_2020Coloured_Material005_0.geometry} material={materials['Subaru_BRZTNR0_2020Coloured_Material.005']} />
            </group>
            <group scale={[0.12, 0.72, 0.29]}>
              <mesh geometry={nodes.Interior_Geo_lodA001_Subaru_BRZTNR0_2020InteriorA_Material001_0.geometry} material={materials['Subaru_BRZTNR0_2020InteriorA_Material.001']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/brz.gltf')
