/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lexyc16 (https://sketchfab.com/Lexyc16)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nissan-skyline-r32-gt-r-8810e677eca543a6b840cf67dd064aa4
title: Nissan Skyline R32 GT-R
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/r32.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.backlight} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.backlight_chrome} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.logo3} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.logo4} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.logo2} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.misc} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.dark_red_glass} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.clear_glass} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.orange_glass} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.red_glass} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.brake_disc} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.brake_disc} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.brake_disc1} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.interior} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.car_paint} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.logo1} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.numberplate} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['nothing.']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.rubber} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.rubber} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.rubber} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.rubber} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.wheel_metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/r32.gltf')
